version: '2.0'
services:
  web_server:
    build: .
    entrypoint: ["python", "run_web_server.py"]
    ports:
    - 5000:5000
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    volumes:
      - .:/group-i

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    expose:
      - "5672"

  scheduler:
    build: .
    entrypoint: ["celery", "-A", "indexer.celery_app", "beat"]
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      BROKER_USER: "guest"
      BROKER_PASSWORD: "guest"
      BROKER_HOST: "rabbitmq"
      BROKER_PORT: "5672"
      BROKER_VHOST: "/"
      FILES_DIR: "files_dir"
    volumes:
      - .:/group-i

  worker:
    build: .
    entrypoint: ["celery", "-A", "indexer.celery_app", "worker"]
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      BROKER_USER: "guest"
      BROKER_PASSWORD: "guest"
      BROKER_HOST: "rabbitmq"
      BROKER_PORT: "5672"
      BROKER_VHOST: "/"
      FILES_DIR: "files_dir"
    volumes:
      - .:/group-i

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    expose:
    - "9200"
    environment:
      discovery.type: single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
    driver: local